package model

// NewTask creates a new task
func NewTask(name, description, poolID string, minAmount float64, taskType TaskType) *Task {
	return &Task{
		Id:          "", // will be generated by the repository layer
		Name:        name,
		Description: description,
		Type:        taskType,
		Criteria: &TaskCriteria{
			MinTransactionAmount: minAmount,
			PoolId:               poolID,
		},
		Status: TaskStatus_TASK_STATUS_ACTIVE,
	}
}
