// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_service.go -package=biz -source=service.go
//

// Package biz is a generated GoMock package.
package biz

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/blackhorseya/pelith-assessment/entity/domain/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskService is a mock of TaskService interface.
type MockTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceMockRecorder
}

// MockTaskServiceMockRecorder is the mock recorder for MockTaskService.
type MockTaskServiceMockRecorder struct {
	mock *MockTaskService
}

// NewMockTaskService creates a new mock instance.
func NewMockTaskService(ctrl *gomock.Controller) *MockTaskService {
	mock := &MockTaskService{ctrl: ctrl}
	mock.recorder = &MockTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskService) EXPECT() *MockTaskServiceMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskService) CreateTask(c context.Context, campaignID string, task *model.Task) (*Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", c, campaignID, task)
	ret0, _ := ret[0].(*Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskServiceMockRecorder) CreateTask(c, campaignID, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskService)(nil).CreateTask), c, campaignID, task)
}

// MockCampaignService is a mock of CampaignService interface.
type MockCampaignService struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignServiceMockRecorder
}

// MockCampaignServiceMockRecorder is the mock recorder for MockCampaignService.
type MockCampaignServiceMockRecorder struct {
	mock *MockCampaignService
}

// NewMockCampaignService creates a new mock instance.
func NewMockCampaignService(ctrl *gomock.Controller) *MockCampaignService {
	mock := &MockCampaignService{ctrl: ctrl}
	mock.recorder = &MockCampaignServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignService) EXPECT() *MockCampaignServiceMockRecorder {
	return m.recorder
}

// StartCampaign mocks base method.
func (m *MockCampaignService) StartCampaign(c context.Context, name string, startAt time.Time, tasks []*Task) (*Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCampaign", c, name, startAt, tasks)
	ret0, _ := ret[0].(*Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartCampaign indicates an expected call of StartCampaign.
func (mr *MockCampaignServiceMockRecorder) StartCampaign(c, name, startAt, tasks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCampaign", reflect.TypeOf((*MockCampaignService)(nil).StartCampaign), c, name, startAt, tasks)
}

// MockRewardService is a mock of RewardService interface.
type MockRewardService struct {
	ctrl     *gomock.Controller
	recorder *MockRewardServiceMockRecorder
}

// MockRewardServiceMockRecorder is the mock recorder for MockRewardService.
type MockRewardServiceMockRecorder struct {
	mock *MockRewardService
}

// NewMockRewardService creates a new mock instance.
func NewMockRewardService(ctrl *gomock.Controller) *MockRewardService {
	mock := &MockRewardService{ctrl: ctrl}
	mock.recorder = &MockRewardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardService) EXPECT() *MockRewardServiceMockRecorder {
	return m.recorder
}

// AllocatePoints mocks base method.
func (m *MockRewardService) AllocatePoints(c context.Context, taskID string, poolID *string, totalPoints int64) ([]*model.PointAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocatePoints", c, taskID, poolID, totalPoints)
	ret0, _ := ret[0].([]*model.PointAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocatePoints indicates an expected call of AllocatePoints.
func (mr *MockRewardServiceMockRecorder) AllocatePoints(c, taskID, poolID, totalPoints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocatePoints", reflect.TypeOf((*MockRewardService)(nil).AllocatePoints), c, taskID, poolID, totalPoints)
}

// RedeemReward mocks base method.
func (m *MockRewardService) RedeemReward(c context.Context, userID, campaignID string, points int64) (*model.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeemReward", c, userID, campaignID, points)
	ret0, _ := ret[0].(*model.Reward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RedeemReward indicates an expected call of RedeemReward.
func (mr *MockRewardServiceMockRecorder) RedeemReward(c, userID, campaignID, points any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeemReward", reflect.TypeOf((*MockRewardService)(nil).RedeemReward), c, userID, campaignID, points)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// RegisterUser mocks base method.
func (m *MockUserService) RegisterUser(c context.Context, username, address string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", c, username, address)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockUserServiceMockRecorder) RegisterUser(c, username, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockUserService)(nil).RegisterUser), c, username, address)
}

// UpdateUserProgress mocks base method.
func (m *MockUserService) UpdateUserProgress(c context.Context, userID, taskID string, completed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProgress", c, userID, taskID, completed)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserProgress indicates an expected call of UpdateUserProgress.
func (mr *MockUserServiceMockRecorder) UpdateUserProgress(c, userID, taskID, completed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProgress", reflect.TypeOf((*MockUserService)(nil).UpdateUserProgress), c, userID, taskID, completed)
}

// MockBacktestService is a mock of BacktestService interface.
type MockBacktestService struct {
	ctrl     *gomock.Controller
	recorder *MockBacktestServiceMockRecorder
}

// MockBacktestServiceMockRecorder is the mock recorder for MockBacktestService.
type MockBacktestServiceMockRecorder struct {
	mock *MockBacktestService
}

// NewMockBacktestService creates a new mock instance.
func NewMockBacktestService(ctrl *gomock.Controller) *MockBacktestService {
	mock := &MockBacktestService{ctrl: ctrl}
	mock.recorder = &MockBacktestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBacktestService) EXPECT() *MockBacktestServiceMockRecorder {
	return m.recorder
}

// RunBacktest mocks base method.
func (m *MockBacktestService) RunBacktest(c context.Context, campaignID string, startTime, endTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunBacktest", c, campaignID, startTime, endTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunBacktest indicates an expected call of RunBacktest.
func (mr *MockBacktestServiceMockRecorder) RunBacktest(c, campaignID, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunBacktest", reflect.TypeOf((*MockBacktestService)(nil).RunBacktest), c, campaignID, startTime, endTime)
}
