// Code generated by MockGen. DO NOT EDIT.
// Source: task.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_task.go -package=query -source=task.go
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"

	model "github.com/blackhorseya/pelith-assessment/entity/domain/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskGetter is a mock of TaskGetter interface.
type MockTaskGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTaskGetterMockRecorder
}

// MockTaskGetterMockRecorder is the mock recorder for MockTaskGetter.
type MockTaskGetterMockRecorder struct {
	mock *MockTaskGetter
}

// NewMockTaskGetter creates a new mock instance.
func NewMockTaskGetter(ctrl *gomock.Controller) *MockTaskGetter {
	mock := &MockTaskGetter{ctrl: ctrl}
	mock.recorder = &MockTaskGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskGetter) EXPECT() *MockTaskGetterMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockTaskGetter) GetByID(c context.Context, id string) (*model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", c, id)
	ret0, _ := ret[0].(*model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskGetterMockRecorder) GetByID(c, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskGetter)(nil).GetByID), c, id)
}

// List mocks base method.
func (m *MockTaskGetter) List(c context.Context, cond ListTaskCondition) ([]*model.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", c, cond)
	ret0, _ := ret[0].([]*model.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskGetterMockRecorder) List(c, cond any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskGetter)(nil).List), c, cond)
}
