// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_transaction.go -package=query -source=transaction.go
//

// Package query is a generated GoMock package.
package query

import (
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionGetter is a mock of TransactionGetter interface.
type MockTransactionGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionGetterMockRecorder
}

// MockTransactionGetterMockRecorder is the mock recorder for MockTransactionGetter.
type MockTransactionGetterMockRecorder struct {
	mock *MockTransactionGetter
}

// NewMockTransactionGetter creates a new mock instance.
func NewMockTransactionGetter(ctrl *gomock.Controller) *MockTransactionGetter {
	mock := &MockTransactionGetter{ctrl: ctrl}
	mock.recorder = &MockTransactionGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionGetter) EXPECT() *MockTransactionGetterMockRecorder {
	return m.recorder
}
