logger:
  level: debug
  format: console

services:
  server:
    http:
      port: 8080

    grpc:
      url: localhost
      port: 50051

    storage:
      dsn: "postgres://root:changeme@db:5432/pelith?sslmode=disable"
