// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/blackhorseya/pelith-assessment/internal/domain/app/command"
	"github.com/blackhorseya/pelith-assessment/internal/domain/app/query"
	"github.com/blackhorseya/pelith-assessment/internal/domain/biz"
	"github.com/blackhorseya/pelith-assessment/internal/domain/infra/composite"
	"github.com/blackhorseya/pelith-assessment/internal/domain/infra/external/etherscan"
	"github.com/blackhorseya/pelith-assessment/internal/domain/infra/storage/mongodb"
	"github.com/blackhorseya/pelith-assessment/internal/domain/infra/storage/pg"
	"github.com/blackhorseya/pelith-assessment/internal/domain/infra/transports/grpc"
	"github.com/blackhorseya/pelith-assessment/internal/domain/infra/transports/http"
	"github.com/blackhorseya/pelith-assessment/internal/shared/configx"
	"github.com/blackhorseya/pelith-assessment/internal/shared/grpcx"
	"github.com/blackhorseya/pelith-assessment/internal/shared/httpx"
	"github.com/blackhorseya/pelith-assessment/internal/shared/mongodbx"
	"github.com/blackhorseya/pelith-assessment/internal/shared/pgx"
	"github.com/blackhorseya/pelith-assessment/pkg/adapterx"
	"github.com/spf13/viper"
	"os"
)

// Injectors from wire.go:

func NewCmd(v *viper.Viper) (adapterx.Server, func(), error) {
	configx, err := initConfigx(v)
	if err != nil {
		return nil, nil, err
	}
	application, err := initAPP(configx)
	if err != nil {
		return nil, nil, err
	}
	injector := &Injector{
		C: configx,
		A: application,
	}
	db, err := pgx.NewClient(application)
	if err != nil {
		return nil, nil, err
	}
	rewardRepoImpl, err := pg.NewRewardRepo(db)
	if err != nil {
		return nil, nil, err
	}
	rewardGetter, err := pg.NewRewardGetter(rewardRepoImpl)
	if err != nil {
		return nil, nil, err
	}
	rewardQueryStore := query.NewRewardQueryStore(rewardGetter)
	campaignRepoImpl, err := pg.NewCampaignRepo(db)
	if err != nil {
		return nil, nil, err
	}
	campaignGetter, err := pg.NewCampaignGetter(campaignRepoImpl)
	if err != nil {
		return nil, nil, err
	}
	transactionRepoImpl, err := pg.NewTransactionRepoImpl(db)
	if err != nil {
		return nil, nil, err
	}
	etherscanTransactionRepoImpl, err := etherscan.NewTransactionRepoImpl(application)
	if err != nil {
		return nil, nil, err
	}
	transactionCompositeRepoImpl := composite.NewTransactionCompositeRepoImpl(transactionRepoImpl, etherscanTransactionRepoImpl)
	transactionRepo := composite.NewTransactionRepoImpl(transactionCompositeRepoImpl)
	userService := biz.NewUserService(campaignGetter, transactionRepo)
	userQueryStore := query.NewUserQueryStore(userService)
	queryController := http.NewQueryController(rewardQueryStore, userQueryStore)
	client, err := grpcx.NewClient(configx)
	if err != nil {
		return nil, nil, err
	}
	campaignServiceClient, err := grpc.NewCampaignServiceClient(client)
	if err != nil {
		return nil, nil, err
	}
	campaignUpdater, err := pg.NewCampaignUpdater(campaignRepoImpl)
	if err != nil {
		return nil, nil, err
	}
	backtestService := biz.NewBacktestService(transactionCompositeRepoImpl)
	transactionAdapter := etherscan.NewTransactionAdapter(etherscanTransactionRepoImpl)
	startCampaignHandler := command.NewStartCampaignHandler(campaignGetter, campaignUpdater, backtestService, transactionAdapter)
	commandController := http.NewCommandController(campaignServiceClient, startCampaignHandler)
	initRoutes := http.NewInitUserRoutesFn(queryController, commandController, campaignServiceClient)
	ginServer, err := httpx.NewGinServer(application, initRoutes)
	if err != nil {
		return nil, nil, err
	}
	campaignService := biz.NewCampaignService()
	mongoClient, cleanup, err := mongodbx.NewClient(application)
	if err != nil {
		return nil, nil, err
	}
	mongodbCampaignRepoImpl := mongodb.NewCampaignRepoImpl(mongoClient)
	campaignCreator := mongodb.NewCampaignCreator(mongodbCampaignRepoImpl)
	createCampaignHandler := command.NewCreateCampaignHandler(campaignService, campaignCreator)
	taskService := biz.NewTaskService()
	taskRepoImpl := pg.NewTaskRepo(db)
	taskCreator := pg.NewTaskCreator(taskRepoImpl)
	addTaskHandler := command.NewAddTaskHandler(campaignService, campaignGetter, taskService, taskCreator)
	campaignDeleter, err := pg.NewCampaignDeleter(campaignRepoImpl)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	runBacktestHandler := command.NewRunBacktestHandler(backtestService, campaignGetter, campaignUpdater, campaignDeleter)
	campaignServiceServer := grpc.NewCampaignServer(createCampaignHandler, addTaskHandler, startCampaignHandler, runBacktestHandler, campaignGetter)
	initServers := grpc.NewInitServersFn(campaignServiceServer)
	healthServer := grpc.NewHealthServer()
	server, err := grpcx.NewServer(application, initServers, healthServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	adapterxServer := newImpl(injector, ginServer, server)
	return adapterxServer, func() {
		cleanup()
	}, nil
}

// wire.go:

const serviceName = "server"

func initConfigx(v *viper.Viper) (*configx.Configx, error) {
	return configx.LoadConfig(v.GetString("config"))
}

func initAPP(config *configx.Configx) (*configx.Application, error) {
	app, err := config.GetService(serviceName)
	if err != nil {
		return nil, err
	}

	if app.Etherscan.APIKey == "" {
		app.Etherscan.APIKey = os.Getenv("ETHERSCAN_API_KEY")
	}

	if app.Infura.ProjectID == "" {
		app.Infura.ProjectID = os.Getenv("INFURA_PROJECT_ID")
	}

	return app, nil
}
